# -*- coding: utf-8 -*-
"""PneumoniaMNIST_LogisticRegression_CNN_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18gxGfFsoOMwzVHfGXwa0skmALQsmYZDy

# PneumoniaMNIST medical ai project

I chose the PneumoniaMNIST dataset from MedMNIST because it is one of the 3 binary and the only non-multimodal/small sample. We have to compare a classical machine learning baseline (I chose using logistic regression) with a small convolutional neural network using PyTorch.

The workflow follows the project rubric so that we have fixed official train/validation/test splits, clear preprocessing, validation-based model selection, final test evaluation, checkpointing, and reproducible outputs.

## 1. install packages
"""

# Install dependencies with:
# pip install -r requirements.txt

"""## 2. imports and setup

"""

import os
import json
import random
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import transforms

import medmnist
from medmnist import INFO

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix, ConfusionMatrixDisplay

from tqdm.auto import tqdm
# reproducibility - seeds used everywhere; please use practices like these in the other chunks
SEED = 123
DATA_FLAG = "pneumoniamnist"
BATCH_SIZE = 64
LEARNING_RATE = 0.001
EPOCHS = 10
OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)

def set_seed(seed):

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

"""## 3. load PneumoniaMNIST metadata

MedMNIST already provides official train, validation, and test splits, that's why i don't split

"""

info = INFO[DATA_FLAG]
DataClass = getattr(medmnist, info["python_class"])

print("dataset:", DATA_FLAG)
print("task:", info["task"])
print("labels:", info["label"])
print("number of channels:", info["n_channels"])
print("number of classes:", len(info["label"]))

"""## 4. load official train, validation, and test splits for PyTorch

"""

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5], std=[0.5]),
])

train_dataset = DataClass(split="train", transform=transform, download=True)
val_dataset = DataClass(split="val", transform=transform, download=True)
test_dataset = DataClass(split="test", transform=transform, download=True)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

print("train size:", len(train_dataset))
print("validation size:", len(val_dataset))
print("test size:", len(test_dataset))

images, labels = next(iter(train_loader))
print("image batch shape:", images.shape)
print("label batch shape:", labels.shape)
print("first labels:", labels[:10].squeeze().tolist())

"""## 5. inspect class balance

"""

def count_labels(dataset):
    labels = dataset.labels.squeeze()
    values, counts = np.unique(labels, return_counts=True)
    return dict(zip(values.astype(int), counts.astype(int)))

class_counts = {
    "train": count_labels(train_dataset),
    "validation": count_labels(val_dataset),
    "test": count_labels(test_dataset),
}

class_counts_df = pd.DataFrame(class_counts).fillna(0).astype(int)
class_counts_df.index = [info["label"][str(i)] for i in class_counts_df.index]
class_counts_df

"""## 6. visualise sample images

"""

images, labels = next(iter(train_loader))

plt.figure(figsize=(10, 4))
for i in range(8):
    image = images[i].squeeze().numpy()
    label = int(labels[i].item())
    label_name = info["label"][str(label)]

    plt.subplot(2, 4, i + 1)
    plt.imshow(image, cmap="gray")
    plt.title(label_name)
    plt.axis("off")

plt.tight_layout()
plt.savefig(OUTPUT_DIR / "sample_images.png", dpi=150)
plt.show()

"""## 7. shared metric function

The same metrics are used for both models to make the comparison fair.

"""

def compute_binary_metrics(y_true, y_pred, y_prob):
    # accuracy measures overall correctness, f1 is useful when classes are imbalanced (it's the harmonic mean) so for nuance it is included. AUC/confusion matrix too

    return {
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "f1": float(f1_score(y_true, y_pred)),
        "auc": float(roc_auc_score(y_true, y_prob)),
        "confusion_matrix": confusion_matrix(y_true, y_pred).tolist(),
    }

def save_json(data, path):
    with open(path, "w") as f:
        json.dump(data, f, indent=4)

"""## 8. prepare flattened arrays for logistic regression

The baseline receives each 28 by 28 image as a flat vector of 784 pixel values.

"""

train_dataset_raw = DataClass(split="train", download=True)
val_dataset_raw = DataClass(split="val", download=True)
test_dataset_raw = DataClass(split="test", download=True)

x_train = train_dataset_raw.imgs.reshape(len(train_dataset_raw), -1).astype(np.float32) / 255.0
x_val = val_dataset_raw.imgs.reshape(len(val_dataset_raw), -1).astype(np.float32) / 255.0
x_test = test_dataset_raw.imgs.reshape(len(test_dataset_raw), -1).astype(np.float32) / 255.0

y_train = train_dataset_raw.labels.squeeze().astype(int)
y_val = val_dataset_raw.labels.squeeze().astype(int)
y_test = test_dataset_raw.labels.squeeze().astype(int)

print("x_train shape:", x_train.shape)
print("y_train shape:", y_train.shape)

"""## 9. train and tune logistic regression baseline

The validation set is used to choose the best value of `C`. The test set is not used during tuning.

"""

c_values = [0.01, 0.1, 1.0, 10.0]

best_baseline = None
best_c = None
best_val_auc = -1
baseline_validation_results = []

for c in c_values:
    model = Pipeline([
        ("scaler", StandardScaler()),
        ("classifier", LogisticRegression(C=c, max_iter=1000, class_weight="balanced")),
    ])

    model.fit(x_train, y_train)

    val_prob = model.predict_proba(x_val)[:, 1]
    val_pred = model.predict(x_val)
    val_metrics = compute_binary_metrics(y_val, val_pred, val_prob)

    baseline_validation_results.append({"C": c, **val_metrics})
    print("C:", c, "validation auc:", val_metrics["auc"])

    if val_metrics["auc"] > best_val_auc:
        best_val_auc = val_metrics["auc"]
        best_c = c
        best_baseline = model

print("best C:", best_c)
print("best validation AUC:", best_val_auc)

"""## 10. final baseline test evaluation

"""

baseline_test_prob = best_baseline.predict_proba(x_test)[:, 1]
baseline_test_pred = best_baseline.predict(x_test)
baseline_test_metrics = compute_binary_metrics(y_test, baseline_test_pred, baseline_test_prob)

joblib.dump(best_baseline, OUTPUT_DIR / "baseline_logistic_regression.joblib")
save_json({
    "model": "logistic_regression",
    "best_C": best_c,
    "validation_results": baseline_validation_results,
    "test_metrics": baseline_test_metrics,
}, OUTPUT_DIR / "baseline_metrics.json")

baseline_test_metrics

"""## 11. define a small CNN

This model is intentionally simple and easy to explain. It has two convolutional blocks followed by a small classifier. This is suitable for 28 by 28 grayscale images and can be modified easily during the oral interview.

"""

class SmallCNN(nn.Module):
    # small cnn for 28 by 28 grayscale pneumonia images
    def __init__(self, num_classes=2):
        super().__init__()

        self.features = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),
        )

        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(32 * 7 * 7, 64),
            nn.ReLU(),
            nn.Linear(64, num_classes),
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

# tensor shape check (the assignment requires checks as good practices, so we should include them as much as possible)
model = SmallCNN().to(device)
dummy_input = torch.randn(4, 1, 28, 28).to(device)
dummy_output = model(dummy_input)

print("dummy input shape:", dummy_input.shape)
print("dummy output shape:", dummy_output.shape)

"""## 12. training and validation functions

"""

def run_one_epoch(model, loader, criterion, optimizer=None, training=False):
    # run one training or evaluation epoch
    if training:
        model.train()
    else:
        model.eval()

    total_loss = 0
    all_labels = []
    all_predictions = []
    all_probabilities = []

    for images, labels in tqdm(loader, leave=False):
        images = images.to(device)
        labels = labels.squeeze().long().to(device)

        if training:
            optimizer.zero_grad()

        with torch.set_grad_enabled(training):
            logits = model(images)
            loss = criterion(logits, labels)

            if training:
                loss.backward()
                optimizer.step()

        probabilities = torch.softmax(logits, dim=1)[:, 1]
        predictions = torch.argmax(logits, dim=1)

        total_loss += loss.item() * images.size(0)
        all_labels.extend(labels.detach().cpu().numpy())
        all_predictions.extend(predictions.detach().cpu().numpy())
        all_probabilities.extend(probabilities.detach().cpu().numpy())

    average_loss = total_loss / len(loader.dataset)
    metrics = compute_binary_metrics(all_labels, all_predictions, all_probabilities)
    metrics["loss"] = float(average_loss)

    return metrics

"""## 13. train CNN with checkpointing


"""

set_seed(SEED)

cnn = SmallCNN(num_classes=2).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(cnn.parameters(), lr=LEARNING_RATE)

best_cnn_val_auc = -1
history = []
checkpoint_path = OUTPUT_DIR / "best_cnn_model.pt"

for epoch in range(1, EPOCHS + 1):
    print(f"epoch {epoch}/{EPOCHS}")

    train_metrics = run_one_epoch(cnn, train_loader, criterion, optimizer=optimizer, training=True)
    val_metrics = run_one_epoch(cnn, val_loader, criterion, optimizer=None, training=False)

    row = {
        "epoch": epoch,
        "train_loss": train_metrics["loss"],
        "train_accuracy": train_metrics["accuracy"],
        "train_auc": train_metrics["auc"],
        "train_f1": train_metrics["f1"],
        "val_loss": val_metrics["loss"],
        "val_accuracy": val_metrics["accuracy"],
        "val_auc": val_metrics["auc"],
        "val_f1": val_metrics["f1"],
    }

    history.append(row)
    print(row)

    # the best checkpoint is selected using validation AUC
    if val_metrics["auc"] > best_cnn_val_auc:
        best_cnn_val_auc = val_metrics["auc"]
        torch.save({
            "model_state_dict": cnn.state_dict(),
            "epoch": epoch,
            "best_val_auc": best_cnn_val_auc,
            "seed": SEED,
            "batch_size": BATCH_SIZE,
            "learning_rate": LEARNING_RATE,
            "epochs": EPOCHS,
            "data_flag": DATA_FLAG,
        }, checkpoint_path)
        print("saved new best checkpoint")

history_df = pd.DataFrame(history)
history_df.to_csv(OUTPUT_DIR / "cnn_training_log.csv", index=False)

print("best cnn validation auc:", best_cnn_val_auc)
print("checkpoint path:", checkpoint_path)

"""## 14. plot CNN training curves

"""

plt.figure(figsize=(8, 5))
plt.plot(history_df["epoch"], history_df["train_loss"], label="train loss")
plt.plot(history_df["epoch"], history_df["val_loss"], label="validation loss")
plt.xlabel("epoch")
plt.ylabel("loss")
plt.title("cnn training and validation loss")
plt.legend()
plt.grid(True)
plt.savefig(OUTPUT_DIR / "cnn_loss_curve.png", dpi=150)
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(history_df["epoch"], history_df["train_auc"], label="train auc")
plt.plot(history_df["epoch"], history_df["val_auc"], label="validation auc")
plt.xlabel("epoch")
plt.ylabel("auc")
plt.title("cnn training and validation auc")
plt.legend()
plt.grid(True)
plt.savefig(OUTPUT_DIR / "cnn_auc_curve.png", dpi=150)
plt.show()

"""## 15. final CNN test evaluation

"""

checkpoint = torch.load(checkpoint_path, map_location=device)

best_cnn = SmallCNN(num_classes=2).to(device)
best_cnn.load_state_dict(checkpoint["model_state_dict"])

cnn_test_metrics = run_one_epoch(best_cnn, test_loader, criterion, optimizer=None, training=False)

save_json({
    "model": "small_cnn",
    "checkpoint": str(checkpoint_path),
    "best_validation_auc": checkpoint["best_val_auc"],
    "test_metrics": cnn_test_metrics,
}, OUTPUT_DIR / "cnn_test_metrics.json")

cnn_test_metrics

"""## 16. compare baseline and CNN

"""

comparison = pd.DataFrame([
    {
        "model": "logistic regression",
        "test_accuracy": baseline_test_metrics["accuracy"],
        "test_f1": baseline_test_metrics["f1"],
        "test_auc": baseline_test_metrics["auc"],
    },
    {
        "model": "small cnn",
        "test_accuracy": cnn_test_metrics["accuracy"],
        "test_f1": cnn_test_metrics["f1"],
        "test_auc": cnn_test_metrics["auc"],
    },
])

comparison.to_csv(OUTPUT_DIR / "model_comparison.csv", index=False)
comparison

"""## 17. confusion matrices

"""

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

ConfusionMatrixDisplay.from_predictions(y_test, baseline_test_pred, ax=axes[0], colorbar=False)
axes[0].set_title("logistic regression")

# get cnn test predictions again for display
best_cnn.eval()
cnn_labels = []
cnn_predictions = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.squeeze().long().to(device)
        logits = best_cnn(images)
        predictions = torch.argmax(logits, dim=1)
        cnn_labels.extend(labels.cpu().numpy())
        cnn_predictions.extend(predictions.cpu().numpy())

ConfusionMatrixDisplay.from_predictions(cnn_labels, cnn_predictions, ax=axes[1], colorbar=False)
axes[1].set_title("small cnn")

plt.tight_layout()
plt.savefig(OUTPUT_DIR / "confusion_matrices.png", dpi=150)
plt.show()
